### ISSUE TITLE
Would welcome a full pre-build docker release

### ISSUE THREAD

**Issue by gdudek** [dstndstn/nova-docker#6]
For those too lazy or distracted to do the build ourselves, a pre-built docker image would be welcome.  Thanks for this repo, regardless.

**Comment by gdudek** [comment]
Found one:  https://hub.docker.com/r/dm90/astrometry/

**Comment by dstndstn** [comment]
Also
https://hub.docker.com/r/astrometrynet/webservice/tags

**Comment by dstndstn** [comment]
Also this repo is deprecated (and I should get rid of it) because there's now a 'docker' directory in the main astrometry.net code repo.
